name: Maven with Spark
description: Combines mvn and spark
inputs:
  title:
    required: true
    description: step title
  script:
    required: true
    description: script to run for step
  jdk:
    required: false
    default: '8'
    description: swap out the jdk
  gpgKey:
    required: false
    default: ""
    description: needed for publish

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: vemonet/setup-spark@v1.2.0 # only needed for hadoop version if / when tests are added 2.4 -> 3.5 builds work
      with:
        spark-version: '3.2.1'
        hadoop-version: '3.2'
        scala-version: '2.13'
    - name: Set up JDK ${{ inputs.jdk }}
      uses: actions/setup-java@v3.12.0
      with:
        java-version: ${{ inputs.jdk }}
        distribution: 'temurin'
        cache: maven #this caches ~/.m2/repo
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: OSSRH_USERNAME # env variable for username in deploy
        server-password: OSSRH_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ inputs.gpgKey }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    - name: ${{ inputs.title }}
      run: ${{ inputs.script }}
      shell: bash