site_name: Shim
site_url: https://sparkutils.github.io/shim/

repo_url: https://github.com/sparkutils/shim/
repo_name: Shim

extra_javascript:
  - js/jquery-3.6.3.min.js
  - js/tagflipper.js

extra_css:
  - stylesheets/site.css

edit_uri: !ENV [MKDOCS_EDIT_URL, ''] # empty disables shows with value enabled -/edit/master/docs/

theme:
  name: material
  logo: img/shim.png
  favicon: img/shim.png
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - content.code.copy

extra:
  version:
    default: latest
    provider: mike

nav:
  - Home: index.md
  - Getting Started:
    - Building and Setting Up: getting_started/index.md
    - Running Shim on Databricks: getting_started/running_on_databricks.md
  - About:
    - History: background/about.md
    - Changelog: background/changelog.md
  - Reference Material:
    - Landing: reference_material.md
    - Maven Site: site/index.html
    - Runtime Scala Docs: site/shim_runtime_3.4.1.oss_3.4_2.12/scaladocs/index.html
    - Compilation Scala Docs: site/shim_compilation_3.4.1.oss_3.4_2.12/scaladocs/index.html

plugins:
  - search:
      prebuild_index: true
      lang: en
  - macros
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true
      enable_creation_date: true
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      cover_subtitle: Less Frustration with Private Spark APIs
      copyright: Copyright @ 2022
      author: Chris Twiner

markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.highlight:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.inlinehilite:
  - meta
  - plantuml_markdown:
      priority: 50
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: sparkutils
      repo: shim
  - pymdownx.saneheaders:
