<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>  <!-- rebuild -->

    <artifactId>shim_compilation_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
    <parent>
        <artifactId>shim_root_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
        <groupId>com.sparkutils</groupId>
        <version>${revision}</version>
    </parent>
    <version>${project.parent.version}</version>
    <name>Shim Compilation</name>
    <description>Compile Shims to ease developing multi version Spark libraries, these should only be used in provided scope</description>
    <packaging>jar</packaging>

    <dependencies>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scalaCompatVersion}</artifactId>
            <version>${sparkVersion}</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/scala</source>
                                <source>src/main/${profileDir}-scala</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>for-scaladocs-etc</id>
                        <phase>pre-site</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/scala</source>
                                <source>src/main/${profileDir}-scala</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/test/scala</source>
                                <source>src/test/${profileDir}-scala</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${mavenJarPluginVersion}</version>
                <configuration>
                    <excludes>
                        <!-- many dbr requires faking the source, we should not include the output -->
                        <exclude>org/apache/spark/sql/catalyst/**</exclude>
                        <exclude>org/apache/spark/sql/internal/**</exclude>
                        <!-- shouldn't be there, really bad for multi-module projects -->
                        <exclude>log4j2.xml</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>

    </build>
</project>
